### ISSUE TITLE
Error not displaying at the good position in templates

### ISSUE THREAD

**Issue by victorgarciaesgi** [vuejs/eslint-plugin-vue#400] opened 2018-02-21 17:00 UTC
Here, the error should display between the brackets but it's highliting the 'result' key

![image](https://user-images.githubusercontent.com/15092120/36493826-c81948e0-1730-11e8-9e63-5c3c75d73a83.png)

Is there a config i'm missing?

Repo of the project: [Moving Mate](https://github.com/victorgarciaesgi/Moving-Mate)

**Comment by mysticatea** [comment] 2018-02-23 11:19
Thank you for the report.

I'm suspecting that it's similar to #383 because the error message doesn't come from ESLint.
Could you make a reproduce case in [our online demo](https://mysticatea.github.io/vue-eslint-demo/)?

**Comment by victorgarciaesgi** [comment] 2018-02-23 12:48
@mysticatea I found the source of the problem. I couldn't reproduced it in your online demo.

<p align="center">
<img src='https://user-images.githubusercontent.com/15092120/36594669-68649cc2-189f-11e8-89ef-c09e4ecb1ffb.png'>
<img src='https://user-images.githubusercontent.com/15092120/36594726-bde00a4c-189f-11e8-875c-3223c7fde4e6.png'>

</p>

If I have a line-break between the 'template' tag and the first html tag, all the eslint error will be shifted by one line

<p align="center">
<img src='https://user-images.githubusercontent.com/15092120/36594750-ce4d72b6-189f-11e8-8317-6e5abb6a8fff.png'>
<img src='https://user-images.githubusercontent.com/15092120/36594756-d3f7c572-189f-11e8-9502-c904d4e0ca45.png'>

</p>

**Comment by mysticatea** [comment] 2018-02-23 13:11
Thank you. In that case, it's an issue in vetur as same as #383. As https://github.com/vuejs/vetur/issues/688 it looks fixed on master branch.

**Closed** 2018-02-23 13:13 UTC
Labels: question
