### ISSUE TITLE
can't extend standard with vue-parser

### ISSUE THREAD

**Issue by dten** [vuejs/eslint-plugin-vue#283] opened 2017-12-06 16:57 UTC
i have settings that work

```
module.exports = {
  root: true,
  parser: 'babel-eslint',
  parserOptions: {
    parser: 'babel-eslint',
    sourceType: 'module'
  },
  env: {
    browser: true,
  },
  // https://github.com/feross/standard/blob/master/RULES.md#javascript-standard-style
  'extends': [
    "standard"
    // want 'plugin:vue/recommended' here but it's not playing ball
  ],
  // required to lint *.vue files
  plugins: [
    'html',
    'vue'
  ],
  // add your custom rules here
  'rules': {
    // allow debugger during development
    'no-debugger': process.env.NODE_ENV === 'production' ? 2 : 0,
    'object-shorthand': ['error', 'always'],
    'comma-dangle': ['error', 'always-multiline'],
    'eol-last': ['error', 'always'],
    'no-multiple-empty-lines': ['error', { 'max': 2, 'maxEOF': 1 }]
  },
}
```

this works and i get messages like 
`  11:22  error  Multiple spaces found before '{'  no-multi-spaces`

if i change the first `  parser: 'babel-eslint',` to `  parser: 'vue-eslint-parser',` as per the instructions i no longer get any lints
if i add `"plugin:vue/recommended"` to the extends i start getting vue related lints, but still no standard lints

I would like both lints :)

these are my package.json versions for lint stuff

```
    "eslint": "^4.12.1",
    "eslint-config-standard": "^10.2.1",
    "eslint-plugin-html": "^4.0.1",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0-beta.2",
```

I'm on Windows 10 with `npm@5.5.1`

**Comment by mysticatea** [comment] 2017-12-07 04:30
Thank you for this issue.

I think that this is a duplicate of #259 and #261.

**Closed by mysticatea** 2017-12-07 04:30 UTC

**Comment by dten** [comment] 2017-12-07 08:07
Thanks!
Given that vue-cli 's default eslintrc file has that in there should probably be a note in the instructions
