### ISSUE TITLE
Add way to ignore files in certain paths for multi-word-component-names

### ISSUE THREAD

**Issue by jewpaltz** [vuejs/eslint-plugin-vue#2579] opened 2024-10-16 12:43 UTC
BH

The rule in [https://github.com/vuejs/eslint-plugin-vue/blob/aa476d619434fba88984604c5fa2d3a530775926/lib/rules/multi-wordcomponentnames.Js] is important. It is part of vue's style guide. However there are exceptions. 

The rule even has an ignore clause. Where you can add certain component names to be ignored. 

However sometimes an entire folder should be ignored. 

For instance, when you are using file based routing. You wouldn't want all of your routes to have multi-word paths. 

So I'm asking for the ignore parameter to also accept paths. Or some other solution that would accomplish the most goal.

**Comment by FloEdelmann** [comment] 2024-10-16 13:01
Duplicate of #2434.

You can use [`overrides`](https://eslint.org/docs/latest/use/configure/configuration-files-deprecated#configuration-based-on-glob-patterns) in `.eslintrc.js`, or [`files`](https://eslint.org/docs/latest/use/configure/configuration-files#specifying-files-and-ignores) in `eslint.config.js`.

**Closed by FloEdelmann** 2024-10-16 13:01 UTC
