### ISSUE TITLE
bind `:=` syntax error on `Windows`

### ISSUE THREAD

**Issue by BachiMjavanadze** [vuejs/eslint-plugin-vue#2453] opened 2024-04-18 11:19 UTC
In my `Vue.js` project (latest version) this makes error: 

    <script setup>
    let imageInfo = {
    	src: "https:/myImg.jpg",
    	alt: "my img",
    	width: 400
    };
    </script>
    
    <template>
    	<img :="imageInfo">
    </template>

it does not likes `:=` syntax. error msg is: 

`'imageInfo' is assigned a value but never used  no-unused-vars`. 

I've disabled this error in `.eslintrc.js`: 

`"no-unused-vars": "off"` 

but it does not helps. 

If I use `imageInfo` inside `<script>`, like this `console.log(imageInfo)` then error disappears.

in `Reprodaction` page it works but on my windows PC it has error (latest `Windows`).

**Comment by FloEdelmann** [comment] 2024-04-18 12:07
Please open a new issue following the "Bug report" template, so we can better track your problem. But I guess it might be a duplicate of #2206, then please see https://github.com/vuejs/eslint-plugin-vue/issues/2206#issuecomment-1578437723 specifically.

**Closed by FloEdelmann** 2024-04-18 12:07 UTC
