### ISSUE TITLE
'v-model' directives aren't supported on <Input> elements?

### ISSUE THREAD

**Issue by thearabbit** [vuejs/eslint-plugin-vue#181] opened 2017-09-08 01:00 UTC
I base `iView`.
I get error

![image](https://user-images.githubusercontent.com/4495160/30191476-2fb3eb3e-946b-11e7-9586-402c993dd3c6.png)

**Comment by armano2** [comment] 2017-09-08 01:02
can you copy error message?

**Comment by thearabbit** [comment] 2017-09-08 01:05
Thanks for you reply
```
[vue-language-server] 'v-model' directives aren't supported on <Input> elements.
Creates a two-way binding on a form input element or a component.
```

**Comment by thearabbit** [comment] 2017-09-08 01:07
The same with `<Select ....>`

**Comment by mysticatea** [comment] 2017-09-08 01:15
Thank you for this issue.

I could not reproduce it on this plugin. Also, the 2nd line doesn't seem the message this plugin generates. It might be the message of `vue-language-server` own.

**Comment by thearabbit** [comment] 2017-09-08 01:18
Excuse me, could advise fixing?

**Comment by armano2** [comment] 2017-09-08 01:19
https://github.com/vuejs/vetur/issues/303

**Comment by armano2** [comment] 2017-09-08 01:23
vetur is using eslint-plugin-vue in version 3.8.0

**Comment by mysticatea** [comment] 2017-09-08 01:33
@thearabbit I'm guessing you are using vscode and vetur. As @armano2 mentioned, please open an issue on there. I'm not sure what happens in the `vue-language-server`.

**Comment by armano2** [comment] 2017-09-08 01:41
i got confirmation from vetur team, they already upgraded version
> https://github.com/vuejs/vetur/blob/master/server/package.json#L21
> The fix will be released in next version, soon.

**Comment by thearabbit** [comment] 2017-09-08 01:50
Look great!
💯

**Comment by thearabbit** [comment] 2017-09-08 01:56
After update, still get error
![image](https://user-images.githubusercontent.com/4495160/30192748-7eb09130-9473-11e7-8a48-99acf00d3bf6.png)

My .eslintrc
```js
{
    "extends": [
        "eslint:recommended",
        "plugin:vue/recommended" // or "plugin:vue/base"
    ],
    "parser": "vue-eslint-parser",
    "parserOptions": {
        "ecmaVersion": 2017,
        "sourceType": "module"
    },
    "rules": {
        "no-console": ["error"],
        "semi": ["error", "always"],
        "quotes": ["error", "single"]
        // override/add rules" settings here
        // "vue/valid-v-if": "error"
    }
}
```

**Comment by HerringtonDarkholme** [comment] 2017-09-08 02:24
Hi @thearabbit, @octref will release new version soon. The current version is 0.9.5.

**Comment by thearabbit** [comment] 2017-09-08 02:28
Oh, thanks again

**Comment by mysticatea** [comment] 2017-09-24 05:08
Could we close this issue?

**Comment by octref** [comment] 2017-09-24 06:26
Don't repro for me on latest.

**Comment by michalsnik** [comment] 2017-10-08 23:13
Ok guys, I'm closing the issue. Feel free to reopen if you'll experience any issues, but if don't get the error when running `eslint` from the console it's most likely an upstream issue, which should rather be addressed in vuetur repository.

**Closed by michalsnik** 2017-10-08 23:13 UTC

**Comment by lovezyg** [comment] 2018-09-27 08:47
mycode is              v-model="xx   | myfilter "     
It warn me， v-model' directives require the attribute value which is valid as LHS.
How to solve this problem?

**Comment by vitorvr** [comment] 2018-10-01 23:47
> mycode is v-model="xx | myfilter "
> It warn me， v-model' directives require the attribute value which is valid as LHS.
> How to solve this problem?

Same here :(

**Comment by zaqisilverano** [comment] 2018-12-04 01:51
> mycode is v-model="xx | myfilter "
> It warn me， v-model' directives require the attribute value which is valid as LHS.
> How to solve this problem?

same here!

**Comment by armano2** [comment] 2018-12-04 02:43
@lovezyg @zaqisilverano @vitorvr i made PR about this bug https://github.com/vuejs/eslint-plugin-vue/pull/699

Please create new ticket next time, no one notice it
