### ISSUE TITLE
No ref as operand in composable

### ISSUE THREAD

**Issue by timothee-durand** [vuejs/eslint-plugin-vue#2615] opened 2024-11-18 16:13 UTC
**Checklist**

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** ^8.49.0
- **eslint-plugin-vue version:** ^9.17.0 (i also tried with ^9.31.0)
- **Vue version:** ^3.4.15
- **Node version:** 20.11.0
- **Operating System:** ubuntu 24

**Please show your full configuration:**

```js
/* eslint-env node */
require('@rushstack/eslint-patch/modern-module-resolution')

module.exports = {
  root: true,
  ignorePatterns: ['*.legacy.vue'],
  env: { node: true, es6: true, browser: true, jest: true },
  extends: [
    'eslint:recommended',
    '@vue/eslint-config-typescript',
    'plugin:vue/vue3-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:import/recommended',
    'plugin:import/typescript',
    '@vue/eslint-config-prettier',
  ],
  parser: 'vue-eslint-parser',
  parserOptions: {
    ecmaVersion: 'latest',
    parser: '@typescript-eslint/parser',
  },
  plugins: ['import', '@typescript-eslint', 'unused-imports'],
  settings: {
    'import/resolver': {
      typescript: {
        alwaysTryTypes: true,
        project: './tsconfig.app.json',
      },
      node: true,
    },
  },
  rules: {
    quotes: [
      'error',
      'single',
      { avoidEscape: true, allowTemplateLiterals: false },
    ],
    '@typescript-eslint/no-explicit-any': 'error',
    '@typescript-eslint/explicit-function-return-type': 'warn',
    'import/newline-after-import': 'error',
    'import/no-unresolved': 'error',
    'import/order': [
      'error',
      {
        'newlines-between': 'always',
        groups: [
          'builtin',
          'external',
          'internal',
          'parent',
          'sibling',
          'index',
        ],
        alphabetize: { order: 'asc', caseInsensitive: true },
      },
    ],
    'no-console': 'warn',
    'no-use-before-define': 'off',
    'no-warning-comments': 'warn',
    'padding-line-between-statements': 'off',
    'unused-imports/no-unused-imports': 'error',
    'vue/no-multiple-template-root': 'off',
    'vue/no-ref-as-operand': 'error',
    'vue/no-undef-components': 'error',
    'vue/html-self-closing': 'off',
    'vue/component-name-in-template-casing': [
      'error',
      'PascalCase',
      {
        registeredComponentsOnly: true,
      },
    ],
  },
  globals: {
    'i18n-t': 'readonly',
  },
}

```

**What did you do?**	

```vue
<script setup>
function useSomething() {
  const testRef = ref('test')
  const testComputed = computed(() => {
    return testRef.value !== 'test'
  })
  return {
    testComputed,
    testRef,
  }
}

const isTestComputedOk = computed(() => {
  const { testComputed } = useSomething()
  if (testComputed) {
    return 'yes'
  } else {
    return 'no'
  }
})
</script>
```

**What did you expect to happen?**
The `testComputed` in the `isTestComputedOk` should throw a `vue/no-ref-as-operand` lint error 

**What actually happened?**
It  doesn't throw

**Repository to reproduce this issue**
https://github.com/timothee-durand/minimal-reproduce-no-ref-as-operand

**Comment by waynzh** [comment] 2024-11-24 03:58
This is a duplicate of #2519.
Thanks for the detailed info. Let's track the issue there.

**Closed by waynzh** 2024-11-24 03:58 UTC
Labels: duplicate
