### ISSUE TITLE
vue/require-default-prop triggers for optional props (TypeScript)

### ISSUE THREAD

**Issue by dmke** [vuejs/eslint-plugin-vue#2306] opened 2023-10-30 12:51 UTC
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** v8.52.0
- **eslint-plugin-vue version:** v9.18.1
- **Node version:** v20.9.0
- **Operating System:** Debian 12

Additionally:

- `@typescript-eslint/eslint-plugin`, v6.9.0
- `typescript`, v5.2.2

**Please show your full configuration:**

`eslint:recommended` + `plugin:vue/vue3-recommended` + `plugin:@typescript-eslint/recommended`.

<details><summary>Contents of <code>.eslintrc.js</code></summary>

```js
module.exports = {
  extends: ["eslint:recommended"],
  env: {
    browser: true,
    es6: true,
  },
  parserOptions: {
    sourceType: "module",
    ecmaVersion: 2022,
  },
  overrides: [{
    parser: "vue-eslint-parser",
    parserOptions: {
      parser: "@typescript-eslint/parser",
      sourceType: "module",
      ecmaVersion: 2022,
    },
    plugins: [
      "@typescript-eslint",
      "vue",
    ],
    files: ["**/*.ts", "**/*.vue"],
    extends: [
      "eslint:recommended",
      "plugin:vue/vue3-recommended",
      "plugin:@typescript-eslint/recommended",
    ],
  }],
}
```

</details>

**What did you do?**	

```vue
<script setup lang="ts">
const props = withDefaults(defineProps<{
  width: number
  height?: number
}>(), {
  width: 100,
})
</script>

<template>
  {{ props }}
</template>
```

**What did you expect to happen?**

`undefined` ought to be a perfectly reasonable default value for the `height` prop, the `vue/require-default-prop` rule should not alert me to set a default.

For reference, this doesn't trigger `vue/require-default-prop` at all:

```vue
<script setup lang="ts">
defineProps<{
  width: number
  height?: number
}>())
</script>
```

**What actually happened?**

```
$ npx eslint UndefinedDefault.vue

/tmp/vue-require-default-prop-repro/UndefinedDefault.vue
  4:3  warning  Prop 'height' requires default value to be set  vue/require-default-prop

✖ 1 problem (0 errors, 1 warning)
```

**Repository to reproduce this issue**

https://github.com/dmke/vue-require-default-prop-repro

**Comment by FloEdelmann** [comment] 2023-10-30 13:14
Duplicate of #2051

**Closed by FloEdelmann** 2023-10-30 13:14 UTC

**Comment by dmke** [comment] 2023-10-30 13:20
Is it a duplicate? I've seen that issue, but I thought it was concerned with props consisting of `ComponentObjectPropsOptions`, i.e.

```ts
defineProps({ name: { type: String, default: undefined } })
```

versus this issue targeting the type annotation, i.e.

```ts
defineProps<{ name?: string }>()
```

**Comment by FloEdelmann** [comment] 2023-10-30 13:22
Hmm, it's not an exact duplicate, but definitely the same root issue. See also the `src/components/DisplayMessageCorrect.vue` example there. Maybe you can comment there to have all information in one place?

**Comment by dmke** [comment] 2023-10-30 13:23
Sure, will do.

Thanks!
