### ISSUE TITLE
Bug token.type.endsWith is not a function

### ISSUE THREAD

**Issue by ldwqh0** [vuejs/eslint-plugin-vue#814] opened 2019-02-12 02:59 UTC
I use proposal-private-methods in a '.vue' file.
``` javascript
  export default class TouristNumber extends Vue {
    #pro1='hello'
  }
```

this is my error
```bash
Module build failed (from ./node_modules/eslint-loader/index.js):
TypeError: token.type.endsWith is not a function
    at isComment (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint-plugin-vue/lib/utils/indent-common.js:187:118)
    at Array.every (<anonymous>)
    at :matches(Program, VElement[parent.type!='VElement']):exit (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint-plugin-vue/lib/utils/indent-common.js:1627:37)
    at listeners.(anonymous function).forEach.listener (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.leaveNode (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/util/node-event-generator.js:303:14)
    at CodePathAnalyzer.leaveNode (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:654:23)
    at CodePathAnalyzer.overrideLeaveNode (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint-plugin-node/lib/rules/process-exit-as-throw.js:123:27)
    at nodeQueue.forEach.traversalInfo (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/linter.js:752:28)
    at Array.forEach (<anonymous>)
    at runRules (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/linter.js:746:15)
    at Linter._verifyWithoutProcessors (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/linter.js:891:31)
    at preprocess.map.textBlock (/home/lidong/Projects/dmzl/sources/web-admin/node_modules/eslint/lib/linter.js:940:35)

 @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib??vue-loader-options!./src/module/dataview-module/component/passengerFlow/Index.vue?vue&type=script&lang=js& 38:0-44 45:19-32
 @ ./src/module/dataview-module/component/passengerFlow/Index.vue?vue&type=script&lang=js&
 @ ./src/module/dataview-module/component/passengerFlow/Index.vue
 @ ./src/module/dataview-module/route/index.js
 @ ./src/module/dataview-module/index.js
 @ ./src/module/index.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8888 (webpack)/hot/dev-server.js @babel/polyfill ./src
```

**Comment by armano2** [comment] 2019-02-12 03:19
what node version are you running this on?

**Comment by ldwqh0** [comment] 2019-02-13 07:04
@armano2 
operation system: ubuntu 18.04
node version : 10.15

**Comment by ota-meshi** [comment] 2019-02-13 10:28
I have debugged this.

When parsing the private property with `babel-eslint`, seems to get the following token.

```ts
Token {
  type: 
   TokenType {
     label: '#',
     keyword: undefined,
     beforeExpr: false,
     startsExpr: false,
     rightAssociative: false,
     isLoop: false,
     isAssign: false,
     prefix: false,
     postfix: false,
     binop: null,
     updateContext: null },
  value: undefined,
  start: 92,
  end: 93,
  loc: SourceLocation { start: { line: 4, column: 0 }, end: { line: 4, column: 1 } },
  range: [ 92, 93 ] }
```

The type property is not a string.

I think we need to report to the `babel-eslint` team.

**Comment by ldwqh0** [comment] 2019-02-14 03:52
There is no problem in my *.js file.
It's only error in my *.vue file.
so ,I think that may be eslint-plugin-vue  bugs.

**Comment by mysticatea** [comment] 2019-02-14 04:14
Yeah, please open an issue on `babel-eslint` repo since this is a bug in `babel-eslint`. In ESLint spec, `Token#type` must be a string.

Closing as not a bug in `eslint-plugin-vue`.

**Closed by mysticatea** 2019-02-14 04:14 UTC

**Comment by mysticatea** [comment] 2019-02-14 04:15
For a reference, the AST spec of ESLint is here: https://eslint.org/docs/developer-guide/working-with-custom-parsers#the-ast-specification

**Comment by ota-meshi** [comment] 2019-02-14 05:29
@ldwqh0 You may be able to provisionally avoid this issue by turning off `vue/script-indent` rule.

**Comment by gdutwyg** [comment] 2021-12-19 11:14
> @ldwqh0 You may be able to provisionally avoid this issue by turning off `vue/script-indent` rule.

yes, it is useful,   so this is babel-eslint's problem?

**Comment by nagwan** [comment] 2022-01-17 00:31
I am having the same issue, any updates?!

**Comment by nagwan** [comment] 2022-01-17 01:09
i faced the same issue and fixed with updating 
`"eslint-plugin-vue": "^8.3.0"`
