### ISSUE TITLE
[bug] undef component in template 

### ISSUE THREAD

**Issue by Valar103769** [vuejs/eslint-plugin-vue#2027] opened 2022-11-02 08:26 UTC
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: ^8.21.0,
- **eslint-plugin-vue version:^9.3.0
- **Node version: 16
- **Operating System:macos

**Please show your full configuration:**

```json5
module.exports = {
  root: true,
  env: {
    node: true
  },
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/eslint-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
    'plugin:vue/vue3-essential',
    '@vue/eslint-config-typescript/recommended',
    'plugin:import/errors',
    'plugin:import/warnings',
    'plugin:import/typescript',
    'plugin:promise/recommended'
  ],
  plugins: ['unused-imports', 'promise'],
  settings: {
    'import/resolver': {
      alias: {
        map: [['@', './src/']],
        extensions: ['.ts', '.js', '.vue']
      }
    }
  },
  parserOptions: {
    ecmaVersion: 2020
  },
  rules: {
    'require-await': 'error',
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'prettier/prettier': [
      'error',
      {
        semi: false,
        singleQuote: true,
        printWidth: 120,
        trailingComma: 'none',
        arrowParens: 'avoid'
      }
    ],
    'unused-imports/no-unused-imports': 'error',
    'import/first': 'error',
    'import/order': [
      'error',
      {
        alphabetize: { order: 'asc', caseInsensitive: true },
        'newlines-between': 'always',
        pathGroups: [
          {
            pattern: '@/**',
            group: 'external',
            position: 'after'
          }
        ]
      }
    ],
    'no-restricted-imports': [
      'error',
      {
        patterns: [
          // no relative imports allowed, always use alias, it makes easier to move files later if necessary
          './**',
          '../**'
        ]
      }
    ],
    '@typescript-eslint/no-unused-vars': 'error'
  },
  overrides: [
    {
      files: ['**/__tests__/*.{j,t}s?(x)', '**/tests/unit/**/*.spec.{j,t}s?(x)'],
      env: {
        jest: true
      }
    },
    {
      files: ['tests/**/*.ts'],
      rules: {
        'no-restricted-imports': 'off'
      }
    }
  ]
}

```

**What did you do?**	

```vue
comment  ` import HelloWorld from '@/components/HelloWorld.vue'` in src/App.vue,
```

**What did you expect to happen?**
emit error  below  <HelloWorld />

**What actually happened?**

eslint output 
[Info  - 16:24:47] ESLint server is starting
[Info  - 16:24:47] ESLint server running in node v16.14.2
[Info  - 16:24:48] ESLint server is running.
[Info  - 16:24:48] ESLint library loaded from: /Users/vayne/toy/my-project1/node_modules/eslint/lib/api.js

**Repository to reproduce this issue**

https://github.com/cstuncsik/vitequality

my Vscode settings
```json
{
  // "terminal.integrated.shellArgs.osx": [],
  "editor.fontSize": 14,
  "editor.quickSuggestions": {
    "strings": true
  },
  "files.exclude": {
    "**/.git": false
  },
  "editor.tabSize": 2,
  "typescript.preferences.quoteStyle": "single",
  // "workbench.colorCustomizations": {
  //   //设置用户选中代码段的颜色
  //   "editor.selectionBackground": "#FFFFFF",
  //   //搜索匹配的背景色
  //   "editor.findMatchBackground": "#ff0000",
  //   "editor.findMatchHighlightBackground": "#ffffff",
  //   "editor.findRangeHighlightBackground": "#ff9900"
  // },
  "editor.codeActionsOnSave": {
    // "source.fixAll.eslint": true,
    // "eslint.autoFixOnSave": true,
    "source.fixAll.stylelint": true

    // "source.organizeImports": true
  },
  // settings.json
  "[html]": {
    "editor.linkedEditing": true
  },
  "[vue]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "vetur.validation.template": false,
  //vue格式化时保证js中的方法后面有空格
  // "vetur.format.defaultFormatter.js": "vscode-typescript",
  "javascript.format.insertSpaceBeforeFunctionParenthesis": true,
  // "javascript.implicitProjectConfig.experimentalDecorators": true,
  "vetur.grammar.customBlocks": {
    "docs": "md",
    "i18n": "json"
  },
  "security.workspace.trust.untrustedFiles": "open",
  // "tabnine.experimentalAutoImports": true,
  "workbench.startupEditor": "none",
  "files.autoSave": "onFocusChange",
  "workbench.iconTheme": "material-icon-theme",
  // "editor.formatOnPaste": true,
  // "editor.formatOnType": true,
  // "[typescript]": {
  //   "editor.defaultFormatter": "esbenp.prettier-vscode"
  // },

  "eslint.format.enable": true,
  "breadcrumbs.showMethods": false,
  "breadcrumbs.showModules": false,
  "breadcrumbs.symbolPath": "off",
  "eslint.alwaysShowStatus": true,
  "eslint.lintTask.enable": true,
  "[json]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[javascript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "[less]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "html",
    "vue"
  ],
  "emmet.syntaxProfiles": {
    "vue-html": "html",
    "vue": "html"
  },
  "files.associations": {
    "*.vue": "vue",
    "*.css": "tailwindcss"
  },

  "GitCommitPlugin.MaxSubjectWords": 30,
  "workbench.colorTheme": "Splus",
  "volar.autoCompleteRefs": true,
  "editor.minimap.enabled": false,
  "typescript.tsserver.pluginPaths": ["typescript-plugin-css-modules"],
  "typescript.preferences.includePackageJsonAutoImports": "on",
  "[typescript]": {
    "editor.defaultFormatter": "esbenp.prettier-vscode"
  },
  "json.schemas": [],
  "eslint.packageManager": "yarn",
  "vite.autoStart": false,
  "volar.icon.preview": false,
  "editor.defaultFormatter": "esbenp.prettier-vscode",
  "editor.linkedEditing": true,
  "workbench.editor.highlightModifiedTabs": true,
  "workbench.preferredDarkColorTheme": "Splus",
  "editor.tabCompletion": "on",

  "workbench.editorAssociations": {
    "*.xlsx": "default"
  },
  "cSpell.caseSensitive": true
}

```

**Comment by ota-meshi** [comment] 2022-11-02 11:12
I can't reproduce it in your repository. Please provide a reproducible repository.

**Comment by Valar103769** [comment] 2022-11-02 11:57
> I can't reproduce it in your repository. Please provide a reproducible repository.

which step do you arrived?  you need use my eslintrc and vscode setting to reproduce

**Comment by ota-meshi** [comment] 2022-11-02 22:28
The lint script in your repo was working fine.
Looking at your log, ESLint seems to work fine.

> comment ` import HelloWorld from '@/components/HelloWorld.vue'` in src/App.vue,

What is this message? At least it looks like a message unrelated to ESLint.

If I can't provide a reproducible repo, I will close this issue.

**Comment by ota-meshi** [comment] 2022-11-02 22:42
There seems to be a hidden message in the markdown you wrote.

> `emit error below <HelloWorld />`

Also, I guessed that `comment ` meant commenting out.

You're probably asking for the following rule:
https://eslint.vuejs.org/rules/no-undef-components.html

However, this rule will also report globally registered components if used as is.
You need to configure the options correctly for your repo.
https://eslint.vuejs.org/rules/no-undef-components.html#options

**Closed by ota-meshi** 2022-11-02 22:42 UTC
Labels: needs repro
