### ISSUE TITLE
Eslint error 'no-undef' appear in the global type

### ISSUE THREAD

**Issue by nicefan** [vuejs/eslint-plugin-vue#1625] opened 2021-09-16 02:06 UTC
![image](https://raw.githubusercontent.com/nicefan/fine/master/no-undef.jpg)

This error only appears in the Vue file, should belong to the syntax in the file is not properly identify the Vue, because this is a typescript syntax,  JS error should not occur.
这个只有在vue文件中出现，应该属于没有正确识别vue文件中的语法，因为这个是一个类型，不应该出现这个js中的错误，是我配置的问题吗

- **ESLint version: 7.32.0** 
- **eslint-plugin-vue version:7.17** 
- **Node version: 14.16.0** 
- **Operating System: win10** 

**Please show your full configuration:**

```json5
{
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: '@typescript-eslint/parser',
    ecmaVersion: 2020,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  env: {
    browser: true,
    node: true,
    es2020: true,
  },
  extends: [
    'eslint:recommended',
    'plugin:vue/vue3-recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:prettier/recommended',
  ]
}
```

**Comment by ota-meshi** [comment] 2021-09-16 02:33
Thank you for posting this issue.
Please provide a repository to reproduce the problem.

**Comment by nicefan** [comment] 2021-09-16 02:54
> Thank you for posting this issue.
> Please provide a repository to reproduce the problem.
add new "*.d.ts" file in project.
add Type declaration to this file:
``` type Obj<T> = Record<string, T>```
then use the type declare to vue file

**Comment by ota-meshi** [comment] 2021-09-16 03:00
If I don't provide a repository, I can't address this issue anymore, So I will close this issue.

**Closed** 2021-09-16 03:30 UTC
Labels: needs info

**Comment by nicefan** [comment] 2021-09-16 03:47
> Thank you for posting this issue.
> Please provide a repository to reproduce the problem.

reproduce repository: https://github.com/nicefan/no-undef.git
'no-undef' error in 'src/App.vue', at 'main.ts' is no problem

vscode enabled Volar0.27.21 plugin
vscode configure:
```JSON
{
  "eslint.format.enable": true,
  "eslint.validate": [
    "javascript",
    "javascriptreact",
    "typescript",
    "typescriptreact",
    "vue"
  ]
}
```

**Comment by ota-meshi** [comment] 2021-09-16 04:05
You need to configure the vue file to turn off the no-undef rule.

```js
  overrides: [
    {
      files: ['*.vue'],
      rules: {
        'no-undef': 'off', // ts(2304)
      }
    }
  ]
```

You don't see a no-undef error in `ts` because you aren't using it rule in your `ts` file.

https://github.com/typescript-eslint/typescript-eslint/blob/b1df8179c64ce9b013f751eb6281b2ffac0229af/packages/eslint-plugin/src/configs/eslint-recommended.ts#L24

The following documentation will also be of interest to you.

https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/FAQ.md#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors

**Comment by nicefan** [comment] 2021-09-16 04:35
thanks , i found 'no-undef':'off' overrides of *.ts in "@typescript-eslint/recommended", so my ts file no proplem, But 
how can I apply this rule to <script lang="ts"> tag of vue file? Whether should it be preset in "plugin:vue/vue3-recommended" ?

**Comment by ota-meshi** [comment] 2021-09-16 05:04
You need to add the following to your `.eslintrc.js`:

```js
  overrides: [
    {
      files: ['*.vue'],
      rules: {
        'no-undef': 'off', // ts(2304)
      }
    }
  ]
```

`"plugin:vue/vue3-recommended"` does not add this configuration as it is also used by js users.
