### ISSUE TITLE
fail to configure rule vue/script-indent in vue-cli

### ISSUE THREAD

**Issue by SilenceZeng** [vuejs/eslint-plugin-vue#373] opened 2018-02-01 09:04 UTC
* **ESLint Version:  4.15.0**
* **eslint-plugin-vue Version: 4.0.0**
* **vue-cli Version: 2.9.2**
* **Node Version:  8.5.0**
I download this plugin from vue-cli's webpack template.the default script-indent is 0,but i want 2 spaces.so i add this rule to the rules in .eslintrc.js:
```
'vue/script-indent': ["error", 2, {"baseIndent": 1}]
```
but it did not work,the eslint throwed indent errors(Expected indentation of 0 spaces but found 2 )

**Comment by mysticatea** [comment] 2018-02-01 09:17
Thank you for the report.

You seem to use `eslint-plugin-vue` 4.0.0. However, the rule was added in 4.2.0: https://github.com/vuejs/eslint-plugin-vue/releases/tag/v4.2.0

**Comment by SilenceZeng** [comment] 2018-02-02 00:51
sorry, it maybe because of other eslint plugin

**Comment by mysticatea** [comment] 2018-02-09 01:46
Closing as answered. Feel free reopen if the problem is not solved.

**Closed by mysticatea** 2018-02-09 01:46 UTC
Labels: question
