### ISSUE TITLE
How can I override only TypeScript script tag in Vue files, excluding JavaScript

### ISSUE THREAD

**Issue by tjx666** [vuejs/eslint-plugin-vue#2217] opened 2023-06-17 19:17 UTC
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version: 8.43.0** 
- **eslint-plugin-vue version: 9.14.1** 
- **Node version:** 18.16.0
- **Operating System:** MacOS

**Please show your full configuration:**

```json5
{
    {
            files: ['*.{ts,tsx}'],
            rules: {
                'no-restricted-syntax': [
                    error,
                    {
                        selector:
                            "VariableDeclaration[kind = 'let'] > VariableDeclarator[init = null]:not([id.typeAnnotation])",
                        message: 'Provide a type annotation.',
                    },
                ],
            },
        }
}
```

**What did you expect to happen?**

I want to only apply rule to only ts/tsx code. 

**What actually happened?**

If I use `files: ['*.{ts,tsx}']`, this will not override ts code in `.vue` file.
If I use `files: ['*.{ts,tsx,vue}']`, this will also lint javascript code in `.vue` file.

**Comment by FloEdelmann** [comment] 2023-06-17 19:34
Duplicate of #2012, please follow that ticket instead. Unfortunately, there is no solution yet.

**Closed by FloEdelmann** 2023-06-17 19:34 UTC
