### ISSUE TITLE
eslint parse typescript syntax error

### ISSUE THREAD

**Issue by HelloSYR** [vuejs/eslint-plugin-vue#1455] opened 2021-03-09 06:05 UTC
I used the following typescript syntax, but got an error

![image](https://user-images.githubusercontent.com/31028597/110425977-4135b300-80e0-11eb-9e89-7bc095e9c59a.png)

![image](https://user-images.githubusercontent.com/31028597/110427195-5d3a5400-80e2-11eb-8c6e-5c829e334c07.png)

**Comment by ota-meshi** [comment] 2021-03-09 07:28
I close this issue because you haven't posted any information to reproduce.

**Closed by ota-meshi** 2021-03-09 07:28 UTC
