### ISSUE TITLE
'vue/html-closing-bracket-spacing' Doesn't Work

### ISSUE THREAD

**Issue by MarkSky** [vuejs/eslint-plugin-vue#933] opened 2019-07-26 05:57 UTC
**Tell us about your environment**	
* **ESLint version: 5.16.0
* **eslint-plugin-vue version: 5.2.3	
* **Node version: 10.16.0	

**Please show your full configuration:**

```
module.exports = {
    root: true,
    env: { browser: true, node: true },
    extends: [
        'plugin:vue/essential',
        'plugin:vue/strongly-recommended',
        'eslint:recommended',
        'plugin:vue/recommended',
    ],
    rules: {
        'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
        'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
        'vue/html-closing-bracket-newline': ['error', { multiline: 'never' }],
        'vue/html-closing-bracket-spacing': [
            'error',
            { selfClosingTag: 'always' },
        ],
        'vue/html-indent': ['error', 4],
        'vue/html-self-closing': [
            'error',
            { html: { void: 'always', normal: 'never' } },
        ],
        'vue/max-attributes-per-line': [
            'error',
            { singleline: 1, multiline: { max: 1, allowFirstLine: true } },
        ],
        'vue/script-indent': ['error', 4, { baseIndent: 1, switchCase: 1 }],
        'vue/singleline-html-element-content-newline': [
            'error',
            { ignores: ['router-link'] },
        ],
    },
    parser: 'vue-eslint-parser',
    parserOptions: {
        parser: 'babel-eslint',
        ecmaVersion: 2018,
        sourceType: 'module',
    },
};


```

**What did you do?**	

```
<template>
    <div class="home">
        <img
            alt="Vue logo"
            src="../assets/logo.png"/>
        <HelloWorld msg="Welcome to Your Vue.js App" />
        <div class="test"></div>
    </div>
</template>

```

**What did you expect to happen?**
```
<template>
    <div class="home">
        <img
            alt="Vue logo"
            src="../assets/logo.png" />
        <HelloWorld msg="Welcome to Your Vue.js App" />
        <div class="test"></div>
    </div>
</template>

```

**What actually happened?**
I set fix when saved file, but the image tag is still not changed.
And I got an error from VSCode: Expected a space before '/>', but not found.
I think the follow rule doesn't work for <img />

> 'vue/html-closing-bracket-spacing': ['error', { selfClosingTag: 'always' }],

**Comment by francescq** [comment] 2019-10-31 12:10
Using prettier + eslint autofix
For me it's missbehaving also:
1- <hr class="MuiCard__separator separator" >
2- Prettier phase: <hr class="MuiCard__separator separator" />
3- Eslint phase: <hr class="MuiCard__separator separator" > 
Expected no space before '>', but found.eslint(vue/html-closing-bracket-spacing)

**Comment by ota-meshi** [comment] 2019-12-28 00:15
Thank you for this issue.

I tried this but could not reproduce. Maybe there was a problem with the old version. Do you still reproduce now?

**Comment by MarkSky** [comment] 2019-12-30 02:05
Sorry, I forgot this question for a long time. I found it was affected by prettier.
After I stopped using prettier, It was solved.

**Closed** 2019-12-30 02:06 UTC
