### ISSUE TITLE
vue/html-quotes fix tool bug

### ISSUE THREAD

**Issue by 759325100** [vuejs/eslint-plugin-vue#2604] opened 2024-11-11 02:57 UTC
vue/html-quotes to fix unexpected problems in the following code

```html
<span :class='{"action": index === 0}'>
```

I got a wrong result

```html
<span :class="{&quot;action&quot;: index === 0}">
```

**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:*8.52.0* 
- **eslint-plugin-vue version:*9.18.0* 
- **Vue version:*2.6.14* 
- **Node version:*16.19.1* 
- **Operating System:*macos* 

**Please show your full configuration:**

```json5
{
  "vue/html-quotes": [ "error", "double"]
}
```

**What did you do?**	

```vue
<span :class='{"action": index === 0}'>
```

**What did you expect to happen?**
```html
<span :class="{'action': index === 0}">
```

**What actually happened?**

```html
<span :class="{&quot;action&quot;: index === 0}">
```
**Repository to reproduce this issue**

**Comment by 759325100** [comment] 2024-11-11 03:03
I think this is a situation that the rule fix tool ignores. If it can be taken into account, the compatibility may be better.

**Comment by waynzh** [comment] 2024-11-11 04:31
Refer to this https://github.com/vuejs/eslint-plugin-vue/issues/2587#issuecomment-2441149617

**Comment by waynzh** [comment] 2024-11-11 04:34
Refer to this https://github.com/vuejs/eslint-plugin-vue/issues/2587#issuecomment-2441149617

**Comment by ota-meshi** [comment] 2024-11-11 04:35
Yeah. It's duplicate of #2587.

**Closed by ota-meshi** 2024-11-11 04:35 UTC
