### ISSUE TITLE
vue/order-in-components can support ts setup

### ISSUE THREAD

**Issue by TerryChenUI** [vuejs/eslint-plugin-vue#2644] opened 2024-12-12 09:56 UTC
it can't not work in when use vue3 typescript setup file, can it support

**Comment by FloEdelmann** [comment] 2024-12-12 10:26
This seems like a duplicate of #1677. See the reasoning there why `vue/order-in-components` won't add support for `<script setup>`.

**Closed by FloEdelmann** 2024-12-12 10:26 UTC
