### ISSUE TITLE
vue/event-name-in-template-casing 

### ISSUE THREAD

**Issue by hqzh** [vuejs/eslint-plugin-vue#1029] opened 2020-01-03 02:21 UTC
to set event name force kebab-case
```
// good

<button @custom-event="handleCustom" /> 

//bad

<button @customEvent="handleCustom" /> 
```

hope support，like props

**Comment by ota-meshi** [comment] 2020-01-06 12:58
Hi.

This issue is a duplicate of #356.
I close this issue.

**Closed by ota-meshi** 2020-01-06 12:58 UTC

**Comment by biesbjerg** [comment] 2020-12-21 09:31
Can this please be reopened? #356 is not about enforcing casing in templates, but about enforcing casing of the events defined in component's `emit`.

**Comment by koooge** [comment] 2021-06-14 10:36
vue/v-on-event-hyphenation works for me.

https://eslint.vuejs.org/rules/v-on-event-hyphenation.html
