### ISSUE TITLE
Does not support `--fix`

### ISSUE THREAD

**Issue by jasonkuhrt** [vuejs/eslint-plugin-vue#1] opened 2016-12-23 02:02 UTC
```
❯ echo "const a = 'single+semi';" > foobar.js
❯ ./node_modules/.bin/eslint --fix foobar.js

  1:7  error  'a' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)

❯ cat foobar.js
const a = "single+semi"
```
```
❯ ccat test.vue
<template>
  <div v-on:click.prevent="activateTab()" v-bind:class="{ active: active }">
    <slot></slot>
  </div>
</template>

<script>
  export default {
    name: 'tab-link',
    data() {
      return {
        storeRegistered: false,
      };
    },
    computed: {
      active() {
        const tab = this.tabs[this.tabGroup];
        const tabName = this.tabName;
        const forceActive = this.forceActive;
        const activeTabName = tab.activeTabName;
        const isActive = !!((tab && activeTabName === tabName) || forceActive);
        return isActive;
      },
      tabs() {
        return this.$store.getters.getTabs;
      },
    },
    props: {
      isDefaultTab: {
        type: Boolean,
      },
      tabGroup: {
        type: String,
        required: true,
      },
      tabName: {
        type: String,
        required: true,
      },
    },
    created() {
      const tab = {};

      tab[this.tabGroup] = {
        activeTabName: this.isDefaultTab ? this.tabName : '',
      };

      if (!this.storeRegistered) {
        this.$store.dispatch('REGISTER_TAB', tab);
        this.storeRegistered = true;
      }
    },
    methods: {
      activateTab() {
        this.$store.dispatch('SET_ACTIVE_TAB', { tabGroup: this.tabGroup, tabName: this.tabName });
      },
    },
  };
</script>

❯ ./node_modules/.bin/eslint --fix test.vue

   9:11  warning  Strings must use doublequote  quotes
  13:8   warning  Extra semicolon               semi
  17:21  error    Unallowed use of `this`       fp/no-this
  17:31  error    Unallowed use of `this`       fp/no-this
  17:45  warning  Extra semicolon               semi
  18:25  error    Unallowed use of `this`       fp/no-this
  18:37  warning  Extra semicolon               semi
  19:29  error    Unallowed use of `this`       fp/no-this
  19:45  warning  Extra semicolon               semi
  20:48  warning  Extra semicolon               semi
  21:79  warning  Extra semicolon               semi
  22:24  warning  Extra semicolon               semi
  25:16  error    Unallowed use of `this`       fp/no-this
  25:43  warning  Extra semicolon               semi
  42:21  warning  Extra semicolon               semi
  44:11  error    Unallowed use of `this`       fp/no-this
  45:24  error    Unallowed use of `this`       fp/no-this
  45:44  error    Unallowed use of `this`       fp/no-this
  45:59  warning  Strings must use doublequote  quotes
  46:8   warning  Extra semicolon               semi
  48:12  error    Unallowed use of `this`       fp/no-this
  49:9   error    Unallowed use of `this`       fp/no-this
  49:30  warning  Strings must use doublequote  quotes
  49:50  warning  Extra semicolon               semi
  50:9   error    Unallowed use of `this`       fp/no-this
  50:36  warning  Extra semicolon               semi
  55:9   error    Unallowed use of `this`       fp/no-this
  55:30  warning  Strings must use doublequote  quotes
  55:60  error    Unallowed use of `this`       fp/no-this
  55:84  error    Unallowed use of `this`       fp/no-this
  55:99  warning  Extra semicolon               semi
  58:4   warning  Extra semicolon               semi

✖ 32 problems (14 errors, 18 warnings)
```

**Comment by trainiac** [comment] 2017-01-17 16:44
This as been more of a eslint-plugin-html / eslint limitation.  But it looks like it's here!

https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/45

Not on a stable version yet but I got it working by using `npm install 'BenoitZugmeyer/eslint-plugin-html#v2'` for the version of eslint-plugin-html

**Comment by znck** [comment] 2017-01-17 16:46
Fixed in #3 

Yet to create a release.

**Closed by znck** 2017-01-17 16:46 UTC

**Comment by smith64fx** [comment] 2017-01-19 16:34
Is there any manual how to use the --fix function?

I'm really fed of things like "Missing space before function parentheses" or "Extra semicolon" xD

**Comment by znck** [comment] 2017-01-19 17:09
@yyx990803 Can we publish a beta release?

**Comment by chrisvfritz** [comment] 2017-01-20 07:59
@znck I'll publish very soon (probably tomorrow).

**Comment by saiberz** [comment] 2017-05-26 03:46
@chrisvfritz btw did you publish it?  maybe can we help a bit to publish it?

**Comment by znck** [comment] 2017-05-26 06:06
It's published.

**Comment by chrisvfritz** [comment] 2017-05-27 03:24
Confirmed. @saiberz Is it not working for you?
