### ISSUE TITLE
Object shorthand property makes `script-indent` rule show error.

### ISSUE THREAD

**Issue by gluons** [vuejs/eslint-plugin-vue#363] opened 2018-01-26 08:14 UTC
![screenshot-2018-1-26 vue js eslint demo](https://user-images.githubusercontent.com/4688092/35430587-88229744-02ab-11e8-9ded-16cf2692b3e4.png)

**Tell us about your environment**

* **ESLint Version:** v4.16.0
* **eslint-plugin-vue Version:** v4.2.0
* **Node Version:** v8.9.4

**Please show your full configuration:**

See on [demo page](https://mysticatea.github.io/vue-eslint-demo/#eJyNVstu2zAQ/BVDl1zMBujRDQoUBfoD7dEXSlpJbChSXZKOlSD/3qGot1KghxjhzHLfu9RbVtiSskv25ApWnf96NartLPvTT9vSd4v/DRl/qti2p4dPjxv04cvVXA3dB/mSKhm0P71dzelkZEuX08O3rns4x3MxXXGXJHDa6o/Q+9W8Q+HT4+hJds44aHLZ5Q1OGuc5FN6ycKEjzi6fz5mxopCOREmFliy9gtRMaOmcwJ+qzYzBnGQShmrxSmwX3JQHUeOspvXRfyDipfHDdRWNrxjPVgummu4TWFIe6nrxvCRNnsRNLggCE5JrtwFSIC21OfGWeaZ+DWhVSCiMGZlQajvfi6JBcgpPnHRtyU56MGYDzof7LmS6e5Yit8iMNNGS3zKOWjUhldTaN2xD3cxQMMVOY61tLvUOVMbA2Y+qqsxNalWmzHYzyjgHCIuXRnlynSzmFLTqTqUYILQD6uxlPqsz9CJc3+ZWT4jNfyMurWcRW3g5s0zJKVoA+DFqnzBHutoFBAF2sbYsl5L5RjmRU2XRkZueDgaztBwQKKF6pWgxXkorQwvHJFHdXK8gJysSlTIIot+h6Hu57tNggoNeLXNaAh5B9OUCISRCE5IrZJdMIU9wSrgGo98grQPI9CcoRNMr0gnBTaGckclkqp3vO7IpvlugR/Qfqzygc5u+a8gsHkYWI9tiP4gSeguvbjQzjW81Gto6ZWqRo8GfyceCzgn6p1AsF85bIRpaY5y9GVUohfFb7E+wnnZyQ81HOzPz291j6tySy4i2ElM1xewE6i42LrcBW6VokDeDweysHhJycDpuWNGxxf044nJjGTWTrsewKTMsvRDbZxRWK9/TrqrCkJ6bQCviV1VrfrtpFnDcNkska37o1PVYjHgcg2iKmC2vCSZHfIOTe0sOuwvw/H6IUnq5EVAlCaoqdIf7j3A9FpyOjsPQFr97WJJiSv+a3I9EhC2XqNxoMD1tMzfNweK1OpLjezn4eSAjOAzK8R6jU2GZyQc2BzYVcR3czAzD9w+rUddH2VvUpEd5PxDDDsO9Ka0zcRM5RIXzvV6DsZG3UFoJU1XYWr/jkqYDiGGTzwcUe4zWDbzGD2C16sEJi9N8AD9Q2OKr6Si4WlwLVBwtd3zEsEpfDmBsS4Dv5ywl/qd6TTfT8Vcf13GWHrxzRvgMsTyC8bvumyl/xPfve/zGO2fDK4SYMzyRTJS9/wViDXBp).

**What did you do? Please include the actual source code causing the issue.**

```vue
<script>
import SomeComponent from './SomeComponent';

export default {
  name: 'App',
  components: {
    SomeComponent
  }
};
</script>
```

**What did you expect to happen?**

Should not see `script-indent` error when use object shorthand property.  
It should preserves indent level.

**What actually happened? Please include the actual, raw output from ESLint.**

```
Expected indentation of 6 spaces but found 2 spaces. (vue/script-indent) 
```

**Comment by mysticatea** [comment] 2018-01-26 08:36
Thank you for this issue.

However, I think this is a duplicate of #359, #352, #347, and #344.
PR #346 has fixed it. Please wait for the next release.

**Closed by mysticatea** 2018-01-26 08:36 UTC

**Comment by gluons** [comment] 2018-01-26 08:50
Oh! Thank you.

![Hooray](https://media.giphy.com/media/11NlXRhFSZl4w8/giphy.gif)

**Comment by michalsnik** [comment] 2018-01-28 22:15
https://github.com/vuejs/eslint-plugin-vue/releases/tag/v4.2.1

**Comment by gluons** [comment] 2018-01-28 23:34
Oh! Thank you so much. 😘
