### ISSUE TITLE
iframe self-closing is invalid

### ISSUE THREAD

**Issue by dchenk** [vuejs/eslint-plugin-vue#505] opened 2018-06-26 17:44 UTC
My environment:
 "eslint": "^4.19.1",
 "eslint-friendly-formatter": "^4.0.1",
 "eslint-import-resolver-webpack": "^0.10.0",
 "eslint-loader": "^2.0.0",
 "eslint-plugin-import": "^2.13.0",
 "eslint-plugin-vue": "^4.5.0",
 "extract-text-webpack-plugin": "^3.0.2"

I'm using MacOS, Node v8.11.3.

My config:
```
"devDependencies": {
    "autoprefixer": "^8.6.3",
    "babel-core": "^6.26.3",
    "babel-eslint": "^8.2.3",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.4",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.7.0",
    "babel-preset-env": "^1.7.0",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.4.1",
    "copy-webpack-plugin": "^4.5.1",
    "css-loader": "^0.28.11",
    "eslint": "^4.19.1",
    "eslint-friendly-formatter": "^4.0.1",
    "eslint-import-resolver-webpack": "^0.10.0",
    "eslint-loader": "^2.0.0",
    "eslint-plugin-import": "^2.13.0",
    "eslint-plugin-vue": "^4.5.0",
    "extract-text-webpack-plugin": "^3.0.2",
    "file-loader": "^1.1.11",
    "friendly-errors-webpack-plugin": "^1.7.0",
    "html-webpack-plugin": "^3.2.0",
    "node-notifier": "^5.1.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^2.1.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.1.0",
    "postcss-loader": "^2.1.5",
    "postcss-url": "^7.3.2",
    "rimraf": "^2.6.0",
    "semver": "^5.3.0",
    "shelljs": "^0.8.2",
    "uglifyjs-webpack-plugin": "^1.2.6",
    "url-loader": "^1.0.1",
    "vue-loader": "^14.2.3",
    "vue-style-loader": "^4.1.0",
    "vue-template-compiler": "^2.5.16",
    "webpack": "^3.11.0",
    "webpack-bundle-analyzer": "^2.13.1",
    "webpack-cli": "^2.1.5",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.3"
}
```

I'm trying to have an `iframe` with a separate closing tag so that it's not self-closing. This is valid HTML.
```vue
<iframe name="some-frame" src="about:blank"></iframe>
```

**What did you expect to happen?**
The iframe elements should be left as is when running lint with the `--fix` option.

**What actually happened?**
The `vue/html-self-closing` rule automatically (and incorrectly) rewrites the `iframe` elements to be self closing.

**Comment by michalsnik** [comment] 2018-07-15 22:47
Hey @dchenk Do you get any error? As far as I remember this is an intended behaviour. `Iframe` is non-void html element, and we can self-close it in Vue. In final HTML it'll have it's own ending tag anyway. Same as with any other HTML element - empty divs are reduced to `<div />` too.

**Comment by dchenk** [comment] 2018-07-16 00:07
@michalsnik my point is that `iframe` elements shouldn't be self-closing even in the Vue template. It's invalid HTML, and in fact the HTML parser that the Vue template compiler uses should fail with an error when it reaches a `<iframe src="something"/>`

The standard (https://www.w3.org/TR/html5/syntax.html#start-tags) states that:
> if the element is one of the void elements, or if the element is a foreign element, then there may be a single U+002F SOLIDUS character (/)

Yet, as you point out, `iframe` elements are not void elements: https://www.w3.org/TR/html5/syntax.html#void-elements

**Comment by michalsnik** [comment] 2018-07-16 22:29
Indeed it is invalid HTML, but vue template compiler compiles is back to `<iframe></iframe`. Self closing tags are just a syntactic sugar that we can use because of that extra compile step. In plain HTML you still have to write closing tags. You can read more about it here: https://vuejs.org/v2/style-guide/#Self-closing-components-strongly-recommended

Spec also doesn't allow custom components to be self-closed yet here we are :) 

If you however don't like the rule - you can disable it. That's ok

**Closed** 2018-09-22 17:59 UTC
Labels: needs info

**Comment by chrisnicola** [comment] 2019-02-06 17:10
@michalsnik why does it matter what the Vue compiler does here? It is invalid HTML and <iframe> is not a custom component it is part of the HTML standard.

Requiring <iframe> to be self closing breaks valid HTML parsers like parse5, which then results in very difficult to diagnose behaviours (basically failing to parse the rest of the document). HTML parsing lik this is necessary for tools such as gettext-extractor when people might be trying to automate i18n work. While disabling this situationally is an option, it is my understanding that the general pupose of a linter is to guide people towards standardization and generally accepted ways of doing things. This seems to do the opposite.

Encouraging people to self close <iframe> when it is not valid HTML is misleading and likely to lead to other problems for them down the road. I would strongly recommend reconsidering this.

**Comment by SebastianNiemann** [comment] 2019-03-11 15:53
@chrisnicola same here.

For me, the current default feels to be problematic for the following reason:

As I understood it, a central statement of VueJS is to _embraces classic web technologies_. Advocating non-HTML (or *vueish* HTML) as standard HTML seems contrary to me. It is just not actual standard HTML anymore, but something different.

I also do not understand the necessity to drop standards compatibility, just to type a handful of characters less in a very specific use case. But I am unsure if *vueish* HTML was actually introduced for this purpose, or actually just meant to gracefully handle old XHTML. In the later case, I would assume to promote the actual standard, instead of further legacy code.

**Comment by pzgz** [comment] 2020-01-24 06:18
For me, putting a self-closing iframe tag in html, will stop event "DOMContentLoaded" from triggering. I just met this bug and trace to this thread. My vue components cannot load since I load them after DOMContentLoaded, after I close the iframe with </ifarme>, the issue was resolved
