### ISSUE TITLE
Dynamic slot using v-for with typescript implicitly has type 'any' 

### ISSUE THREAD

**Issue by Moonlight63** [vuejs/eslint-plugin-vue#1773] opened 2022-01-23 13:54 UTC
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:**7.32.0 
- **eslint-plugin-vue version:**8.3.0
- **Node version:**v16.3.0
- **Operating System:**Ubuntu

**Please show your full configuration:**

```json5
module.exports = {
  root: true,

  env: {
    node: true
  },

  globals: {
    defineProps: 'readonly',
    defineEmits: 'readonly'
  },

  extends: [
    '@vue/standard',
    'plugin:vue/vue3-recommended',
    '@vue/typescript/recommended',
    'plugin:prettier/recommended'
  ],

  parser: 'vue-eslint-parser',

  parserOptions: {
    parser: '@typescript-eslint/parser'
  },

  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'no-unused-vars': process.env.NODE_ENV === 'production' ? 'warn' : 'off',
    'vue/component-name-in-template-casing': [
      'warn',
      'PascalCase',
      {
        registeredComponentsOnly: false,
        ignores: []
      }
    ],
    'vue/v-on-event-hyphenation': [
      'error',
      'never',
      {
        autofix: true
      }
    ],
    'vue/attribute-hyphenation': ['error', 'never']
  }
}

```

**What did you do?**	

```vue
          <slot
            name="tbody"
            :index="rowIndex"
            :row="row"
          >
            <slot
              v-for="(column) in tableColumns"
              :name="`datatable-tbody-td-${column.idx}`"
              :column="column"
              :row="row"
              :uniqueId="uniqueId"
            >
              <TableBodyCell
                :key="`datatable-tbody-td-${uniqueId()}-${column.label}`"
                :name="column.key"
                :data-label="column.label"
                v-text="row[column.key]"
              />
            </slot>
          </slot>
```

**What did you expect to happen?**
I am creating dynamic slots for each element in an array and using an id from the array object to create the name of the slot. This works perfectly fine, except that eslint is giving a type error on the 'column' variable created by the for loop, and because this is happening in the template, I can't just assert the type. I am using vue 3 with typescript.

**What actually happened?**

![Screenshot from 2022-01-23 04-27-58](https://user-images.githubusercontent.com/7518189/150681868-2120727c-2e80-4138-ada0-20bbfdcd9c60.png)
![Screenshot from 2022-01-23 04-28-54](https://user-images.githubusercontent.com/7518189/150679415-970270e9-6959-45f0-a662-79e67f20697d.png)
![Screenshot from 2022-01-23 04-29-54](https://user-images.githubusercontent.com/7518189/150679419-c787fbf4-871a-45f2-a694-b3b379200992.png)
![Screenshot from 2022-01-23 05-56-40](https://user-images.githubusercontent.com/7518189/150681924-ebeb9690-5035-45f6-90d7-d9a57a19e9ac.png)

**Repository to reproduce this issue**

https://github.com/Moonlight63/pihole-admin-pro/blob/feature/typescript/src/components/Tables/Datatables/DataTable.vue
This file line 345 in this branch.

Thank you for your time.

**Comment by FloEdelmann** [comment] 2022-01-23 14:39
That is not caused by ESLint, but by TypeScript (see `ts(7022)` in the error hover popup).

It sounds like there is indeed a bug in Vue's TypeScript implementation in this case. Please open another issue at https://github.com/vuejs/core. Please also link to this issue from there.

I'll close this issue, but feel free to comment if there is new information.

**Comment by Moonlight63** [comment] 2022-01-23 22:04
Whoops, my bad. Thanks!

**Closed** 2022-01-24 05:50 UTC
