### ISSUE TITLE
Allow html-indent to start with 0 indent

### ISSUE THREAD

**Issue by rightaway** [vuejs/eslint-plugin-vue#360] opened 2018-01-24 19:07 UTC
`html-indent` requires something like

```html
<template>
  <div>
    <div>
      ...
    </div>
  </div>
</template>
```

I'd like an option where it's possible to have it like this, where the first element under the template has no indent (lined up with `template` tag), and everything under that is indented normally. When you have large templates that are nested deeply, saving that first level of indentation saves space. It also allows being consistent with the rules for the `<script>` tags which allow things underneath it to start with an indentation level of 0.

```html
<template>
<div>
  <div>
    ...
  </div>
</div>
</template>
```

**Comment by mysticatea** [comment] 2018-01-25 01:50
Thank you for the issue.

I think this is a duplicate of #292. Please track that.

**Closed by mysticatea** 2018-01-25 01:50 UTC
