### ISSUE TITLE
Fixed an issue that caused an error when set empty string in vue/require-default-prop

### ISSUE THREAD

**Issue by allan2coder** [vuejs/eslint-plugin-vue#999] opened 2019-12-06 08:06 UTC
**Tell us about your environment**	
* **ESLint version: 6.1.0**	
* **eslint-plugin-vue version: 5.2.2**	
* **Node version:10.16.0**	

**Please show your full configuration:**

```json

```

**What did you do?**	

when i run `./node_modules/.bin/eslint --fix` for this following code
```vue
export default {
    props: {
        test: '',
    },
}
```
it will converted to this following code
```
export default {
    props: {
        test: ,
    },
}
```

**What did you expect to happen?**
Don't converted it

**What actually happened?**

**Comment by ota-meshi** [comment] 2019-12-06 09:19
Thank you for this issue.

This is a bug, but closes because it is a duplicate of #993.

**Closed by ota-meshi** 2019-12-06 09:19 UTC
