### ISSUE TITLE
A custom Vue component does not work

### ISSUE THREAD

**Issue by vporton** [vuejs/eslint-plugin-vue#1403] opened 2021-01-01 12:00 UTC
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 6.8.0
- **eslint-plugin-vue version:** 7.4.0
- **Node version:** 12.16.2
- **Operating System:** Ubuntu 20.10

**Please show your full configuration:**
```json5
{
  "extends": [
    "standard",
    "standard-react",
    "plugin:prettier/recommended",
    "prettier/standard",
    "prettier/react",
    "plugin:@typescript-eslint/eslint-recommended",
    "plugin:vue/recommended"
  ],
  "env": {
    "node": true
  },
  "parserOptions": {
    "ecmaVersion": 2020,
    "ecmaFeatures": {
      "legacyDecorators": true,
      "jsx": true
    }
  },
  "settings": {
    "react": {
      "version": "16"
    }
  },
  "rules": {
    "space-before-function-paren": 0,
    "react/prop-types": 0,
    "react/jsx-handler-names": 0,
    "react/jsx-fragments": 0,
    "react/no-unused-prop-types": 0,
    "import/export": 0
  }
}
```

**What did you do?**	

A custom Vue component does not work.

`test.vue`:
```vue
<script>
import { Address } from './test2.vue'

export default {
  name: 'Donate',
  components: {
    Address
  }
}
</script>

<template>
  <div>
    <p>
      <Address
        value=""
        onchange="await setTokenAddress(event.target.value)"/>
    </p>
  </div>
</template>
```

`test2.vue`:
```vue
<template>
    <div>
    </div>
</template>

<script>
export {
  Address: {
    name: "Address",
  },
}
</script>
```

**What actually happened?**

```
npx eslint --plugin vue test.vue

/home/porton/Projects/donations/donations-widget-vue/html/test.vue
  14:5   warning  '<p>' should have end tag                                                                                                                                                                                            vue/html-end-tags
  14:5   warning  Require self-closing on HTML elements (<p>)                                                                                                                                                                          vue/html-self-closing
  15:1   warning  Expected indentation of 4 spaces but found 6 spaces                                                                                                                                                                  vue/html-indent
  16:1   warning  Expected indentation of 6 spaces but found 8 spaces                                                                                                                                                                  vue/html-indent
  17:1   warning  Expected indentation of 6 spaces but found 8 spaces                                                                                                                                                                  vue/html-indent
  17:61  warning  Expected 1 line break before closing bracket, but no line breaks found                                                                                                                                               vue/html-closing-bracket-newline
  17:61  warning  Expected a space before '/>', but not found                                                                                                                                                                          vue/html-closing-bracket-spacing
  18:5   error    Parsing error: x-invalid-end-tag                                                                                                                                                                                     vue/no-parsing-error
  18:6   error    Parsing error: Unexpected closing tag "p". It may happen when the tag has already been closed by another tag. For more info see https://www.w3.org/TR/html5/syntax.html#closing-elements-that-have-implied-end-tags  prettier/prettier

✖ 9 problems (2 errors, 7 warnings)
  0 errors and 7 warnings potentially fixable with the `--fix` option.
```

**Comment by ota-meshi** [comment] 2021-01-01 12:59
I can't reproduce your problem.  Can you share a repository to reproduce the problem?

**Comment by vporton** [comment] 2021-01-01 13:06
> I can't reproduce your problem. Can you share a repository to reproduce the problem?

I can't reproduce your problem. Can you share a repository to reproduce the problem?

**Comment by ota-meshi** [comment] 2021-01-01 13:21
> > I can't reproduce your problem. Can you share a repository to reproduce the problem?
>
> I can't reproduce your problem. Can you share a repository to reproduce the problem?

I don't know what you're talking about, so I close this issue.

**Comment by vporton** [comment] 2021-01-01 13:28
> I can't reproduce your problem. Can you share a repository to reproduce the problem?

Sorry, I sent a wrong reply. The repo is here:
https://github.com/vporton/vue-widget-bug

Please reopen.

**Comment by ota-meshi** [comment] 2021-01-01 23:53
Are you saying that the problem is getting a Parsing error? If so, the problem is putting the `<Address>` tag inside the `<p>` tag. This is an HTML specification. `.vue` is not strictly HTML, but users use tools that take advantage of the HTML ecosystem.  
It may be possible to fix `vue-eslint-parser` to distinguish between the `<Address>` and `<address>` tags, but the problem remains that `prettier` cannot parse.
I close this issue as it is similar to #1300.

**Closed by ota-meshi** 2021-01-01 23:53 UTC
Labels: needs info
