### ISSUE TITLE
Getting a value from the `props` in root scope of `<script setup>` will cause the value to lose reactivity wtith toRef on an object

### ISSUE THREAD

**Issue by tlemaireCDAD** [vuejs/eslint-plugin-vue#2267] opened 2023-08-04 08:16 UTC
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 8.46.0
- **eslint-plugin-vue version:** 9.16.1
- **Node version:** 18.17.0
- **Operating System:** windows 10

**Please show your full configuration:**
module.exports = {
  // https://eslint.org/docs/user-guide/configuring#configuration-cascading-and-hierarchy
  // This option interrupts the configuration hierarchy at this file
  // Remove this if you have an higher level ESLint config file (it usually happens into a monorepos)
  root: true,

  parserOptions: {
    ecmaVersion: "2021", // Allows for the parsing of modern ECMAScript features
  },

  env: {
    node: true,
    browser: true,
    "vue/setup-compiler-macros": true,
  },

  // Rules order is important, please avoid shuffling them
  extends: [
    // Base ESLint recommended rules
    // 'eslint:recommended',

    // Uncomment any of the lines below to choose desired strictness,
    // but leave only one uncommented!
    // See https://eslint.vuejs.org/rules/#available-rules
    // "plugin:vue/vue3-essential", // Priority A: Essential (Error Prevention)
    // 'plugin:vue/vue3-strongly-recommended', // Priority B: Strongly Recommended (Improving Readability)
    "plugin:vue/vue3-recommended", // Priority C: Recommended (Minimizing Arbitrary Choices and Cognitive Overhead)

    // https://github.com/prettier/eslint-config-prettier#installation
    // usage with Prettier, provided by 'eslint-config-prettier'.
    "prettier",
  ],

  plugins: [
    // https://eslint.vuejs.org/user-guide/#why-doesn-t-it-work-on-vue-files
    // required to lint *.vue files
    "vue",

    // https://github.com/typescript-eslint/typescript-eslint/issues/389#issuecomment-509292674
    // Prettier has not been included as plugin to avoid performance impact
    // add it as an extension for your IDE
  ],

  globals: {
    ga: "readonly", // Google Analytics
    cordova: "readonly",
    __statics: "readonly",
    __QUASAR_SSR__: "readonly",
    __QUASAR_SSR_SERVER__: "readonly",
    __QUASAR_SSR_CLIENT__: "readonly",
    __QUASAR_SSR_PWA__: "readonly",
    process: "readonly",
    Capacitor: "readonly",
    chrome: "readonly",
  },

  // add your custom rules here
  rules: {
    "prefer-promise-reject-errors": "off",
    // "vue/no-setup-props-destructure": "off",

    // allow debugger during development only
    "no-debugger": process.env.NODE_ENV === "production" ? "error" : "off",
  },
};

```json5

```

**What did you do?**	

```vue
const props = defineProps({
  formData: {
    type: Object,
    required: true
  },
  qrCode: {
    type: String,
    default: ""
  },
});
const addQrcode = toRef(props, "qrCode"); // OK
const id = toRef(props.formData, "id"); // WARNING
```

**What did you expect to happen?**
no warning for an object

**What actually happened?**
Warning for an object and no alert for a string
Getting a value from the `props` in root scope of `<script setup>` will cause the value to lose reactivity.eslint[vue/no-setup-props-destructure](https://eslint.vuejs.org/rules/no-setup-props-destructure.html)

**Repository to reproduce this issue**

**Comment by ota-meshi** [comment] 2023-08-04 09:03
Duplicate of #2259

**Closed by ota-meshi** 2023-08-04 09:03 UTC
