### ISSUE TITLE
TypeError: token.type.endsWith is not a function when having multiline v-show statement with `!` on the start of one of the lines.

### ISSUE THREAD

**Issue by ndyakov** [vuejs/eslint-plugin-vue#396] opened 2018-02-16 18:57 UTC
**Tell us about your environment**

* **ESLint Version: 4.17.0**
* **eslint-plugin-vue Version:4.2.2**
* **Node Version: 9.3.0**

**Please show your full configuration:**

```

module.exports = {
    "env": {
        "browser": true,
        "es6": true,
        "amd": true
    },
    "parser": "vue-eslint-parser",
    "parserOptions": {
        "parser": "babel-eslint",
        "sourceType": "module",
        "allowImportExportEverywhere": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:vue/recommended"
    ]
};

```

**What did you do? Please include the actual source code causing the issue.**

```vue
<template>
                  <a class="class" @click="handler(index)"
                    v-show="something > 3 &&
                    !somethingElse[index]">{{OtherThing}}</a>
</template>
```

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
```
Token {
  type:
   TokenType {
     label: '!',
     keyword: undefined,
     beforeExpr: true,
     startsExpr: true,
     rightAssociative: false,
     isLoop: false,
     isAssign: false,
     prefix: true,
     postfix: false,
     binop: null,
     updateContext: null },
  value: '!',
  start: 7539,
  end: 7540,
  loc:
   SourceLocation {
     start: { line: 141, column: 20 },
     end: { line: 141, column: 21 } },
  range: [ 7539, 7540 ] }
token.type.endsWith is not a function
TypeError: token.type.endsWith is not a function
    at isComment (/project/node_modules/eslint-plugin-vue/lib/utils/indent-common.js:186:118)
    at Array.every (<anonymous>)
    at EventEmitter.:matches(Program, VElement[parent.type!='VElement']):exit (/project/node_modules/eslint-plugin-vue/lib/utils/indent-common.js:1502:37)
    at EventEmitter.emit (events.js:159:13)
    at NodeEventGenerator.applySelector (/project/node_modules/vue-eslint-parser/index.js:2730:26)
    at NodeEventGenerator.applySelectors (/project/node_modules/vue-eslint-parser/index.js:2744:22)
    at NodeEventGenerator.leaveNode (/project/node_modules/vue-eslint-parser/index.js:2755:14)
    at traverse (/project/node_modules/vue-eslint-parser/index.js:117:13)
    at traverseNodes (/project/node_modules/vue-eslint-parser/index.js:120:5)
    at scriptVisitor.Program:exit (/project/node_modules/vue-eslint-parser/index.js:3188:25)
```

This `!` in the start of the line somehow made eslint throw this error. 

This may be https://github.com/mysticatea/vue-eslint-parser bug. Let me know if I should move it there.

**Comment by mysticatea** [comment] 2018-02-17 06:22
Thank you for this report. However, this looks a duplicate of #349. It's a bug in `babel-eslint`. Please track that issue.

**Closed by mysticatea** 2018-02-17 06:22 UTC
