### ISSUE TITLE
error  Use the latest vue-eslint-parser in .js file

### ISSUE THREAD

**Issue by jasonxia23** [vuejs/eslint-plugin-vue#325] opened 2018-01-04 13:16 UTC
**Tell us about your environment**

* **ESLint Version:** 4.14.0
* **eslint-plugin-vue Version:** 4.0.1
* **Node Version:** 8.9

**Please show your full configuration:**

```json
{
  "extends": ["./node_modules/@my/eslintconfig"],
  "parser": "babel-eslint",
  "parserOptions": {
    "sourceType": "module",
    "ecmaVersion": 6,
    "allowImportExportEverywhere": true
  },
  "plugins": [
    "html"
  ]
}
```

In `./node_modules/@my/eslintconfig`
```js
module.exports = {
  plugins: ['vue'],
  parser: 'vue-eslint-parser',
  parserOptions: {
    parser: 'babel-eslint',
    allowImportExportEverywhere: false,
    sourceType: 'module',
    ecmaVersion: 2017,
    ecmaFeatures: {
      globalReturn: false,
      impliedStrict: false,
      jsx: false,
      experimentalObjectRestSpread: false
    },
  },
  extends: [
    'plugin:vue/strongly-recommended'
  ],
};
```

**What did you do? Please include the actual source code causing the issue.**

The error throw in every `.js` file

**What did you expect to happen?**

**What actually happened? Please include the actual, raw output from ESLint.**
```bash
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-bind
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/attribute-hyphenation
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/html-indent
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/html-self-closing
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/max-attributes-per-line
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/mustache-interpolation-spacing
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/no-duplicate-attributes
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/no-template-key
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/no-textarea-mustache
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/no-unused-vars
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/require-component-is
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/require-v-for-key
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/v-bind-style
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/v-on-style
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/html-end-tags
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-cloak
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-else-if
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-else
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-for
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-html
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-if
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-model
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-on
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-once
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-pre
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-show
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/valid-v-text
  1:1  error  Use the latest vue-eslint-parser. See also https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error  vue/no-multi-spaces
```

**Comment by filipalacerda** [comment] 2018-01-04 13:30
@jasonxia23 would this help? https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error

**Comment by jasonxia23** [comment] 2018-01-04 14:18
@filipalacerda nope.

**Comment by mysticatea** [comment] 2018-01-06 07:19
Thank you for this issue.

I think that this is a duplicate of #259, #261, #283, and #285.
Please read https://github.com/vuejs/eslint-plugin-vue#what-is-the-use-the-latest-vue-eslint-parser-error.

**Closed by mysticatea** 2018-01-06 07:19 UTC
Labels: duplicate, question

**Comment by armano2** [comment] 2018-12-24 01:18
@bretonio https://vuejs.github.io/eslint-plugin-vue/user-guide/#what-is-the-use-the-latest-vue-eslint-parser-error
