### ISSUE TITLE
Parsing error: Unexpected token ','.

### ISSUE THREAD

**Issue by bosens-China** [vuejs/eslint-plugin-vue#815] opened 2019-02-13 06:42 UTC
**Tell us about your environment**	
* **ESLint version:** ^5.8.0
* **eslint-plugin-vue version:** "^5.0.0"
* **Node version:**	^10.05

**Please show your full configuration:**

```javascript
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/essential',
    '@vue/airbnb',
  ],
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'error' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'error' : 'off',
  },
  parserOptions: {
    parser: 'babel-eslint',
  },
  "globals": {
    "url": true,
  }
};

```

**What did you do?**	

```vue
<template slot="operation" slot-scope="text, record, index">
</template>
```

**What did you expect to happen?**

**What actually happened?**
vs code Error
Parsing error: Unexpected token ','.

**Comment by mysticatea** [comment] 2019-02-13 06:55
Hi. Thank you for this issue.

This is duplicate of #722 and fixed in https://github.com/vuejs/eslint-plugin-vue/commit/97a51b25b9b2a7a37bbe246bbbe4e907618fe317.
Please wait for the next release.

cc: @michalsnik

**Closed by mysticatea** 2019-02-13 06:55 UTC
