### ISSUE TITLE
`TypeError: require is not a function` when running `npm run docs:watch` locally

### ISSUE THREAD

**Issue by Lehoczky** [vuejs/eslint-plugin-vue#2492] opened 2024-06-29 11:19 UTC
I've tried to contribute to the documentation, but when I run `npm run docs:watch`, I only get a blank page with the following error:

```
Uncaught TypeError: require is not a function
    at index.js:9:9
```

![image](https://github.com/vuejs/eslint-plugin-vue/assets/31937175/d28628da-a2e3-455b-a094-1b2702f1bc79)

What I did:
- installed dependencies with `npm install`
- ran `npm run docs:watch`

I've also tried to build the library with `npm run tsc`, but got the following error:

```
lib/rules/order-in-components.js:265:25 - error TS7006: Parameter 'fixer' implicitly has an 'any' type.

265     function* handleFix(fixer, propertyNode, unorderedPropertyNode) {
                            ~~~~~


Found 1 error in lib/rules/order-in-components.js:265
```

I'm on:
- Windows 10
- Node v20.15.0

**Comment by ota-meshi** [comment] 2024-06-30 02:03
I don't use Windows so I don't know what the problem is 🤔 
The `require` function should be resolved in the vite plugin we make, so the problem may be here.

https://github.com/vuejs/eslint-plugin-vue/blob/d7169e10e8e8ac2906c6c4a8bc444fa2b841cd8d/docs/.vitepress/vite-plugin.mts#L23

**Comment by ota-meshi** [comment] 2024-06-30 02:06
> I've also tried to build the library with npm run tsc, but got the following error:

We don't constantly monitor tsc errors, we just look at them occasionally and fix them.



https://eslint.vuejs.org/developer-guide/#jsdoc-type-checking-with-typescript

**Comment by Lehoczky** [comment] 2024-06-30 14:01
It looks like Vite is not processing the library files because the `libRoot` variable has Windows file separators in them, but Vite passes file paths to plugins with linux file separators.

This will always be true:

```ts
async transform(code, id) {
   if (!id.startsWith(libRoot)) {
        return undefined
    }
}
```

Because:
`libRoot` is  `"C:/Users/.../Projects/eslint-plugin-vue/lib"`
but Vite passes this path as the `id` parameter: `"C:\Users\...\Projects\eslint-plugin-vue\lib"`

**Closed** 2024-07-01 08:14 UTC
