### ISSUE TITLE
Used component is falsely recognized as 'not-used'

### ISSUE THREAD

**Issue by trajche18** [vuejs/eslint-plugin-vue#849] opened 2019-03-07 11:09 UTC
**Tell us about your environment**	
* **ESLint version:** 5.15.1	
* **eslint-plugin-vue version:** 5.2.2	
* **Node version:**	10.12.29

**What did you do?**	

I imported the vue component from the right path.
```vue
import **VCheckbox** from '@/components/common/VCheckbox'

export default {
  components: {
    VCheckbox
  },
```
Afterwards, I actually used the component, as seen below:
```vue
  .add('VCheckbox', () => ({
    components: { VCheckbox },
    template:
      '<v-stats-card :items="items" label="I agree to the Terms and Conditions" ' +
      ':rules="[v => !!v || \'You must agree with the terms and conditions in order to continue.\']" ' +
      'arialabel="You must agree with the terms." ' +
      '@click="onClicked(\'checkbox clicked\')" />',
    methods
  }))
```

**What actually happened?**

I get the following error-msg: ESLint: The VCheckbox component has been registered but not used (vue/no-unused-components).

**Comment by FloEdelmann** [comment] 2023-05-16 15:12
Please provide a link to a repository where this issue can be reproduced. The code above looks like non-standard syntax. I'll close this issue now, since it's very old. Feel free to comment more information or open a new issue.

**Closed by FloEdelmann** 2023-05-16 15:12 UTC
