### ISSUE TITLE
Definition for rule 'vue/script-setup-uses-vars' was not found.

### ISSUE THREAD

**Issue by leonheess** [vuejs/eslint-plugin-vue#1578] opened 2021-07-22 09:20 UTC
**Checklist**

- [x] I have tried restarting my IDE and the issue persists.
- [x] I have read the [FAQ](https://eslint.vuejs.org/user-guide/#faq) and my problem is not listed.

**Tell us about your environment**

- **ESLint version:** 7.31.0
- **eslint-plugin-vue version:** 7.14.0
- **Node version:** 14.17.3
- **Operating System:** Windows 10

**Please show your full configuration:**

```json5
module.exports = {
  ignorePatterns: [
    '.*',
    '*.config.js'
  ],
  env: {
    'es6': true,
    'browser': true,
    'node': true,
  },
  plugins: [
    'cypress',
    'prettier',
    'eslint-plugin-no-inline-styles',
  ],
  extends: [
    'eslint:recommended',
    'plugin:cypress/recommended',
    'prettier',
  ],
  rules: {
    'prettier/prettier': 'error',
    'linebreak-style': ['error', 'unix'],
    'no-console': 'warn',
    'no-debugger': 'warn',
    'no-unused-vars': [
      'error',
      {
        'ignoreRestSiblings': true
      }
    ],
    'prefer-const': ['error', {
      'destructuring': 'any',
      'ignoreReadBeforeAssign': false
    }],
    'no-inline-styles/no-inline-styles': 'error',
    'spaced-comment': ['error', 'always', { 'line': { 'exceptions': ['-', '+', '-', '*', '#'] } }],
    'capitalized-comments': [
      'error',
      'always',
      {
        'ignorePattern': 'noinspection|ignored|prettier-ignore',
        'ignoreConsecutiveComments': true
      }
    ]
  },
  overrides: [
    {
      'files': [
        '__tests__/*.{j,t}s?(x)',
        'tests/unit/**/*.spec.{j,t}s?(x)',
      ],
      'env': {
        'jest': true,
      }
    }
  ]
}

```

**What actually happened?**
Error on every page: `Definition for rule 'vue/script-setup-uses-vars' was not found.`

**Comment by ota-meshi** [comment] 2021-07-22 10:02
I can't reproduce your problem. I close this issue because your configuration doesn't seem to use eslint-plugin-vue in the first place.

If you can't solve the problem using eslint-plugin-vue, open a new issue and share your repository where you can reproduce the problem.

**Closed by ota-meshi** 2021-07-22 10:02 UTC

**Comment by leonheess** [comment] 2021-07-22 11:54
Sorry, I forgot some files - see edit

**Comment by rehack** [comment] 2021-08-09 15:54
`script setup` is Syntax sugar of vue3
When vue2 project use this rule `vue/script-setup-uses-vars`，that mean if your `eslint-plugin-vue` version >= v7.13.0,
an error will occur
